### ISSUE TITLE
No pipeline parsing failure on ivalid rules

### ISSUE THREAD

**Issue by WatcherWhale** [WatcherWhale/gogl-ci#2]
Some pipelines get parsed when they should not:

```yaml
job:
  rules:
    - invalid
```

produces this error in GitLab, but does not fail gogl pipeline parsing:

> jobs:job rules should be an array containing hashes and arrays of hashes
